# Generated by Django 4.2.21 on 2025-10-23 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Изображение')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8, verbose_name='Общая стоимость блюда')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Без глютена')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Веганское')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Вегетарианское')),
                ('total_calories', models.PositiveIntegerField(default=0, editable=False, help_text='Автоматически рассчитывается из ингредиентов', verbose_name='Общая калорийность (ккал)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда создано')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('average_price', models.DecimalField(decimal_places=2, help_text='Средняя цена за 100 грамм (1 единицу) в рублях', max_digits=8)),
                ('unit', models.CharField(choices=[('GRAM', 'г'), ('KILOGRAM', 'кг'), ('PIECE', 'шт'), ('TABLESPOON', 'ст.л.')], default='GRAM', max_length=15, verbose_name='Единица измерения')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Ккал на 100 грамм (1 единицу) продукта', null=True, verbose_name='Калорийность на 100г (1 единицу)')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(choices=[('GLUTEN_FREE', 'Без глютена'), ('VEGAN', 'Веган'), ('VEGETARIAN', 'Вегетарианец'), ('NONE', 'Нет ограничений')], default='NONE', max_length=20, verbose_name='Тип диеты')),
                ('weekly_budget', models.DecimalField(decimal_places=2, default=2000.0, help_text='Недельный бюджет на продукты в рублях', max_digits=8)),
                ('meal_swaps_remaining', models.PositiveIntegerField(default=3, verbose_name='Количество замен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Количество в единицах измерения (1 единица = 100г)', max_digits=8, verbose_name='Количество (в единицах)')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='favorites.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorites.ingredient')),
            ],
            options={
                'unique_together': {('dish', 'ingredient')},
            },
        ),
    ]
