# Generated by Django 4.2.21 on 2025-10-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Plan', max_length=100, verbose_name='Название тарифа')),
                ('period', models.CharField(choices=[('1m', '1 month'), ('3m', '3 months'), ('6m', '6 months')], default='1m', max_length=2, verbose_name='Срок')),
                ('persons', models.PositiveIntegerField(default=1, verbose_name='Количество персон')),
                ('breakfast', models.BooleanField(default=False, verbose_name='Завтраки')),
                ('lunch', models.BooleanField(default=False, verbose_name='Обеды')),
                ('dinner', models.BooleanField(default=False, verbose_name='Ужины')),
                ('desserts', models.BooleanField(default=False, verbose_name='Десерты')),
                ('allergy_fish', models.BooleanField(default=False, verbose_name='Рыба и морепродукты')),
                ('allergy_meat', models.BooleanField(default=False, verbose_name='Мясо')),
                ('allergy_grains', models.BooleanField(default=False, verbose_name='Зерновые')),
                ('allergy_honey', models.BooleanField(default=False, verbose_name='Продукты пчеловодства')),
                ('allergy_nuts', models.BooleanField(default=False, verbose_name='Орехи и бобовые')),
                ('allergy_dairy', models.BooleanField(default=False, verbose_name='Молочные продукты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorites.userprofile')),
            ],
        ),
    ]
