# Generated by Django 4.2.21 on 2025-10-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_mealtariff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='is_vegetarian',
        ),
        migrations.AddField(
            model_name='dish',
            name='diet_type',
            field=models.CharField(choices=[('CLASSIC', 'Классическое'), ('LOW_CARB', 'Низкоуглеводное'), ('VEGETARIAN', 'Вегетарианское'), ('KETO', 'Кето')], default='CLASSIC', max_length=20, verbose_name='Тип меню'),
        ),
        migrations.AddField(
            model_name='mealtariff',
            name='diet_type',
            field=models.CharField(choices=[('CLASSIC', 'Классическое'), ('LOW_CARB', 'Низкоуглеводное'), ('VEGETARIAN', 'Вегетарианское'), ('KETO', 'Кето')], default='CLASSIC', max_length=20, verbose_name='Тип меню'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Изображение'),
        ),
    ]
