# Generated by Django 4.2.21 on 2025-10-25 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0004_remove_dish_is_gluten_free_remove_dish_is_vegan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Рецепт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealtariff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_tariff', to=settings.AUTH_USER_MODEL),
        ),
    ]
