# Generated by Django 5.2.7 on 2025-10-25 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0005_dish_recipe_alter_mealtariff_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата меню')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Завтрак'), ('LUNCH', 'Обед'), ('DINNER', 'Ужин'), ('SNACK', 'Перекус')], max_length=20, verbose_name='Тип приема пищи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favorites.dish', verbose_name='Блюдо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ежедневное меню пользователя',
                'verbose_name_plural': 'Ежедневные меню пользователей',
                'unique_together': {('user', 'date', 'meal_type')},
            },
        ),
    ]
