# Generated by Django 5.2.7 on 2025-10-25 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0006_userdailymenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_swap_reset',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Последнее обновление замен'),
            preserve_default=False,
        ),
    ]
