# Generated by Django 5.2.7 on 2025-10-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0007_userprofile_last_swap_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Завтрак'), ('LUNCH', 'Обед'), ('DINNER', 'Ужин'), ('SNACK', 'Перекус')], default='LUNCH', max_length=20, verbose_name='Тип приема пищи'),
        ),
    ]
