# Generated by Django 5.2.7 on 2025-10-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0008_dish_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diet_type',
            field=models.CharField(choices=[('CLASSIC', 'Классическое'), ('LOW_CARB', 'Низкоуглеводное'), ('VEGETARIAN', 'Вегетарианское'), ('KETO', 'Кето')], default='CLASSIC', max_length=20, verbose_name='Тип меню'),
        ),
    ]
