# Generated by Django 5.2.7 on 2025-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0009_alter_userprofile_diet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_dish_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если установлено, показываются только блюда дешевле этой цены', max_digits=8, null=True, verbose_name='Макс. цена за блюдо'),
        ),
    ]
