# Generated by Django 5.2.7 on 2025-10-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0010_userprofile_max_dish_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDailyMenu',
        ),
    ]
