# Generated by Django 5.2.7 on 2025-10-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0011_delete_userdailymenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='diet_type',
        ),
    ]
