# Generated by Django 5.2.7 on 2025-10-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0012_remove_userprofile_diet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtariff',
            name='period',
        ),
        migrations.RemoveField(
            model_name='mealtariff',
            name='persons',
        ),
    ]
