# Generated by Django 5.2.7 on 2025-10-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0013_remove_mealtariff_period_remove_mealtariff_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название аллергена')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Аллерген',
                'verbose_name_plural': 'Аллергены',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='allergies',
            field=models.ManyToManyField(blank=True, help_text='Аллергены, которые содержатся в этом блюде', to='favorites.allergy', verbose_name='Содержит аллергены'),
        ),
    ]
